# Generated by Django 5.1.6 on 2025-02-27 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTypeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detection_name', models.CharField(max_length=50, verbose_name='检测项目具体名称')),
                ('normal_range', models.CharField(blank=True, max_length=50, null=True, verbose_name='检测结果正常范围')),
                ('unit_of_measurement', models.CharField(blank=True, max_length=50, null=True, verbose_name='检测结果计量单位')),
                ('feature_field', models.CharField(max_length=50, verbose_name='检测项目相关特征字段')),
                ('creator_instructions', models.TextField(blank=True, null=True, verbose_name='创建者说明信息')),
            ],
            options={
                'verbose_name': '检测项目类型映射',
                'verbose_name_plural': '检测项目类型映射',
            },
        ),
        migrations.CreateModel(
            name='DeviceRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_deployment_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='设备部署地址')),
                ('device_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='设备类型')),
                ('device_number', models.CharField(max_length=50, verbose_name='设备编号')),
                ('device_remark', models.TextField(blank=True, null=True, verbose_name='设备备注信息')),
                ('coop_org_user_records_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='所属体检机构外键')),
            ],
            options={
                'verbose_name': '设备库存记录',
                'verbose_name_plural': '设备库存记录',
            },
        ),
        migrations.CreateModel(
            name='ArticleRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=50, verbose_name='科普文章内容')),
                ('article_content', models.TextField(verbose_name='科普文章内容')),
                ('detection_project_type_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.testtypemapping', verbose_name='关键词')),
            ],
            options={
                'verbose_name': '科普文章',
                'verbose_name_plural': '科普文章',
            },
        ),
    ]
