# Generated by Django 5.1.6 on 2025-02-13 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_model', models.CharField(max_length=10)),
                ('unit_name', models.CharField(blank=True, max_length=100)),
                ('unit_no', models.CharField(max_length=20)),
                ('mac_addr', models.CharField(max_length=20)),
                ('device_no', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BloodPressure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=200)),
                ('user_id', models.CharField(max_length=20)),
                ('login_type', models.CharField(max_length=1)),
                ('hrR_s', models.IntegerField()),
                ('sbpR_n', models.CharField(max_length=20)),
                ('measure_time', models.DateTimeField()),
                ('dbpR_s', models.IntegerField()),
                ('dbpR', models.IntegerField()),
                ('sbpR', models.IntegerField()),
                ('hrR', models.IntegerField()),
                ('birthday', models.CharField(blank=True, max_length=10)),
                ('age', models.IntegerField()),
                ('sbpR_s', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=1)),
                ('hrR_n', models.CharField(max_length=20)),
                ('record_no', models.CharField(max_length=20)),
                ('dbpR_n', models.CharField(max_length=20)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syd_store.device')),
            ],
        ),
        migrations.CreateModel(
            name='BloodOxygen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xy_n', models.CharField(max_length=20)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('user_id', models.CharField(max_length=20)),
                ('login_type', models.CharField(max_length=1)),
                ('measure_time', models.DateTimeField()),
                ('birthday', models.CharField(blank=True, max_length=10)),
                ('bpm', models.IntegerField()),
                ('xy_s', models.IntegerField()),
                ('xy', models.IntegerField()),
                ('age', models.IntegerField()),
                ('bpm_n', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('bpm_s', models.IntegerField()),
                ('sex', models.CharField(max_length=1)),
                ('record_no', models.CharField(max_length=20)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syd_store.device')),
            ],
        ),
        migrations.CreateModel(
            name='HeightWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('user_id', models.CharField(max_length=20)),
                ('login_type', models.CharField(max_length=1)),
                ('measure_time', models.DateTimeField()),
                ('bmi_s', models.IntegerField()),
                ('bmi', models.FloatField()),
                ('height', models.FloatField()),
                ('nation', models.CharField(max_length=20)),
                ('birthday', models.DateField()),
                ('weight', models.FloatField()),
                ('age', models.IntegerField()),
                ('weight_n', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('weight_s', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('sex', models.CharField(max_length=1)),
                ('department', models.CharField(max_length=100)),
                ('record_no', models.CharField(max_length=20)),
                ('bmi_n', models.CharField(max_length=20)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syd_store.device')),
            ],
        ),
    ]
