# Generated by Django 5.1.6 on 2025-02-19 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syd_store', '0002_remove_bloodpressure_device_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='设备编号'),
        ),
        migrations.AlterField(
            model_name='device',
            name='mac_addr',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='设备MAC地址'),
        ),
        migrations.AlterField(
            model_name='device',
            name='unit_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='单位名称'),
        ),
        migrations.AlterField(
            model_name='device',
            name='unit_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='单位编号'),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='birthday',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='syd_store.device', verbose_name='所属设备'),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='login_type',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='登录类型'),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='measure_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='测量时间'),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='record_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='记录编号'),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='sex',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='性别'),
        ),
    ]
