# Generated by Django 5.1.6 on 2025-02-27 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
        ('syd_store', '0003_alter_device_device_no_alter_device_mac_addr_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTransactionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(help_text='建档模式下，用户ID应为手机号，有助于后续和用户小程序匹配；游客模式下，用户ID默认为时间+随机数（例20250224141944225）', max_length=50, verbose_name='用户的唯一标识')),
                ('physical_examination_time', models.DateTimeField(auto_now_add=True, verbose_name='体检的具体时间')),
                ('coop_org_user_records_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='体检机构的唯一标识')),
                ('device_records_id', models.ForeignKey(help_text='设备没有则自动建立数据', on_delete=django.db.models.deletion.PROTECT, to='management.devicerecords', verbose_name='体检设备的唯一标识')),
                ('test_type_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.testtypemapping', verbose_name='检测项目的唯一标识')),
            ],
            options={
                'verbose_name': '体检事务表',
                'verbose_name_plural': '体检业务事务表（主表）',
            },
        ),
        migrations.CreateModel(
            name='UserCheckupSingleRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_key', models.CharField(help_text='如xy、hr等', max_length=50, verbose_name='关联检测类型')),
                ('text_value', models.CharField(help_text="如'96'，'阴性'等", max_length=255, verbose_name='关联检测的值')),
                ('unit_of_measurement', models.CharField(help_text='从检测项目类型表中获取', max_length=50, verbose_name='字段单位')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('test_info_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='syd_store.testtransactioninfo', verbose_name='事务表外键')),
            ],
            options={
                'verbose_name': '体检业务表',
                'verbose_name_plural': '体检业务表（子表）',
            },
        ),
    ]
