# Generated by Django 5.1.6 on 2025-02-27 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgCustomTestSchemeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='自定义套餐名称')),
                ('detection_projects', models.TextField(blank=True, null=True, verbose_name='包含的检测项目类型')),
                ('description', models.TextField(blank=True, null=True, verbose_name='套餐详细描述')),
                ('coop_org_user_records_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='所属机构外键')),
            ],
            options={
                'verbose_name': '机构自定义检测项目方案',
                'verbose_name_plural': '机构自定义检测项目方案',
            },
        ),
    ]
