# Generated by Django 5.1.6 on 2025-02-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=255, verbose_name='操作所涉及的表名')),
                ('data_id', models.IntegerField(verbose_name='操作的数据的 ID')),
                ('operator_id', models.IntegerField(verbose_name='操作人员的 ID')),
                ('before_data', models.JSONField(verbose_name='操作前的数据')),
                ('after_data', models.JSONField(verbose_name='操作后的数据')),
                ('operation_time', models.DateTimeField(auto_now_add=True, verbose_name='操作发生的具体时间')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
            },
        ),
    ]
